### ISSUE TITLE
Move to actions

### ISSUE THREAD

**Issue by ietf-mpls-yang** [ietf-mpls-yang/te#10]
ACTION-Items:
1. Move RW leafs to state-only
2. Model leafs as identity vs. boolean
3. remove forced-switch-tunnel
4. ACTIONs will be defined by Italo. Italo to update and send out new version.
    ACTIONS are under tunnel
     Additional context provided in the IN arguments

LSP:
  switch-state
   ON, OFF, FAILED, IN-PROGRESS

ACTION: 
 IN:
  Tunnel, LSP
 OUT: 
  Success

       |  |  |     +--rw protection-external-commands
       |  |  |     |  +--rw lockout-of-protection?   boolean
XX: ACTION applied on the tunnel on and result will be maintained under LSP

       |  |  |     |  +--rw manual-switch
XX: boolean at the moment.

       |  |  |     |  |  +--rw manual-switch?         boolean
XX: Similar to forced switch but with lower priority. Switch occurs **only** if some conditions on secondary path PASS
XX: Result of RPC/action completion will be kept in the state

       |  |  |     |  |  +--rw manual-switch-tunnel?   te:tunnel-ref
       |  |  |     |  +--rw forced-switch
       |  |  |     |     +--rw forced-switch?         boolean
       |  |  |     |     +--rw forced-switch-tunnel?   te:tunnel-ref
XX: both are same --> remove the forced-switch-tunnel

**Comment by italobusi** [comment]
I think that the following container has been already removed from the latest YANG tree:

 ```
      |  |  |     +--rw protection-external-commands
       |  |  |     |  +--rw lockout-of-protection?   boolean
       |  |  |     |  +--rw manual-switch
       |  |  |     |  |  +--rw manual-switch?         boolean
       |  |  |     |  |  +--rw manual-swith-tunnel?   te:tunnel-ref
       |  |  |     |  +--rw forced-switch
       |  |  |     |     +--rw forced-switch?         boolean
       |  |  |     |     +--rw forced-swith-tunnel?   te:tunnel-ref

```
Need also to remove the grouping protection-external-commands from the YANG file: see pull request #11

**Comment by ietf-mpls-yang** [comment]
This is closed as addressed already
