### ISSUE TITLE
Configuration of the APS identifier

### ISSUE THREAD

**Issue by italobusi** [ietf-mpls-yang/te#12]
https://github.com/ietf-mpls-yang/te/blob/52f3f2f0feb1da4327f12832fdd8afe2f2da6fb5/rsvp_te_model.tree#L395-L396

When multiple Tunnels shared the protection resources and ITU-T APS signaling is used, there is a need to configure the identifier used by APS to identify each tunnel (normal traffic) when coordinating protection switching.

Since ITU-T APS signaling applies to multiple technologies, it is worthwhile having this attribute in the TE Tunnel model.

If not applicable to all cases, what about using a YANG feature to mark this as optional?

The tree could be updated as follows:

```
       |  |     +--rw shared-resources-tunnels
       |  |     |  +--rw lsp-shared-resources-tunnel*   te:tunnel-ref
       |  |     |  +--rw aps-signal-id?                   uint8

```

**Comment by ietf-mpls-yang** [comment]
Need clarification on whether tunnel leaf-ref is enough? why the extra aps-signal-id?

**Comment by ietf-mpls-yang** [comment]
in secondary path, add aps-id there
AI (Italo): will push this update

**Comment by italobusi** [comment]
Done: see updated pull request #14

**Comment by ietf-mpls-yang** [comment]
incorporated
