### ISSUE TITLE
lsp-shared-resources-tunnel in the LSP state

### ISSUE THREAD

**Issue by italobusi** [ietf-mpls-yang/te#13]
https://github.com/ietf-mpls-yang/te/blob/52f3f2f0feb1da4327f12832fdd8afe2f2da6fb5/rsvp_te_model.tree#L611-L612

The lsp-shared-resources-tunnel is a property of the path (already exist in the path state) and not of an LSP.

As far as I have understood, this information should be in the path state only.

In the LSP state, there should be a pointer to the Tunnel which is actually using the LSP resources.

The following leaf should replace the lsp-shared-resources-tunnel in the LSP state:

`       |  |  |     |  |     +--ro tunnel-using-lsp-resources?       te:tunnel-ref`

**Comment by ietf-mpls-yang** [comment]
change the LSP to have only 1 entry

**Comment by ietf-mpls-yang** [comment]
Addressed
