### ISSUE TITLE
disjointness usage in te-tunnel and path computation RPC

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-mpls-yang/te#17]
How the leaf "disjointness" is used inside the common-constraints_config grouping of ietf-te-types.yang ? This is used in named-path-constraints (pointed by tunnel paths e.g. primary-path) and in the tunnel container. In the path computation it is used both in the  request fro a single path and in the synchronization information for multiple paths. 
It's not clear what the disjointness leaf is referred to, as there is no identifier of another tunnel (for example) to be diverse from. So the first question is : what is the physical resource from which the path should be disjointed ? 

Carlo, Italo, Francesco and Sergio

**Comment by ietf-mpls-yang** [comment]
can be addressed with association group per tunnel

**Comment by ietf-mpls-yang** [comment]
AI (Tarek): will look into bringing the association from bidirectional container

**Comment by ietf-mpls-yang** [comment]
Look into the "not shared risk group"

**Comment by italobusi** [comment]
Italo/Sergio: we have checked the latest updates of the model and get some further questions

The generic-path-disjointness grouping has been added to the te-types module and the description looks quite clear now and applies to the primary and secondary paths of a TE tunnel.

This (generic-path-disjointness) grouping is used by the generic-path-constraints grouping in the te-types module and by the path-constraints_config in the te module.

The latter (path-constraints_config) is used in the definitions of the primary and secondary paths of a TE tunnel while the former (generic-path-constraints) is used by path computation RPC and by the underlay container in the TE topology.

The use of the generic-path-disjointness grouping within the generic-path-constraints grouping is not needed in path computation RPC. Is it needed in TE Topology?

If not needed, it is proposed to remove it from the generic-path-constraints grouping.

**Comment by ietf-mpls-yang** [comment]
to check further if grouping connectivity-matrix-entry-path-attributes is applicable on per tunnel (i.e. working and protecting path) or only per path. If former, the disjointness applies the protecting path

**Comment by ietf-mpls-yang** [comment]
AI: usecase description is needed for disjointness in  connectivity-matrix-entry-path

**Comment by ietf-mpls-yang** [comment]
AI (Tarek): look into moving disjointness from this grouping

**Comment by ietf-mpls-yang** [comment]
We looked into this. The agreement was to leave the disjointness in the common grouping as-is.
NOTE: the disjointness can apply to synchronized computation for multiple paths (e.g. primary)

One usecase for multiple primary in OTN (Francesco):
 Virtual concatenation
 need to be able to specify that primary paths co-routed

Tunnel
**PICK 2 primary-paths RED, ...., srlg**
PRIMAY List
  Path1 (BEST)
    constraints1 (node-diverse, IRO, affinity)
    secondary-list-leafref
  Path2 (NEXT-BEST)
    constraints2 (srlg-diverse, IRO, affinity)
    secondary-list-leafref
  Path3 (NEXT-BEST)
    constraints2 (node-diverse)
    secondary-list-leafref

SECONDARY List

**Comment by ietf-mpls-yang** [comment]
AI(Tarek): bring back the disjointness under the generic-path grouping
Path computation module can do a customized grouping
If disjointness is set on a PRIMARY path then
  applies to all secondary paths
NOTE: the disjointness set under a SECONDARY overrides the one under primary path.

Add a new: single-path-constraints grouping
The multiple path constraints is the existing generic grouping

**Comment by italobusi** [comment]
See #35

**Comment by ietf-mpls-yang** [comment]
Please see/review commit 4796fad for merge of the changes
