### ISSUE TITLE
performance data to add in te-tunnel and te-mpls 

### ISSUE THREAD

**Issue by ylee-tx** [ietf-mpls-yang/te#19]
During the last IETF meeting when I present ietf-te-kpi-telemetry model, Pavan asked if the KPI data have been defined in the TE-tunnel model or other places. As a follow-on to this comment,  I raised an issue during the call in the last week as to how add performance data in the te-tunnel model. In the ietf-te-kpi-temetry model, we have the following augmentation: 

module: ietf-te-kpi-telemetry
  augment /te:te/te:tunnels/te:tunnel/te:state:
    +--ro te-telemetry
       +--ro id?                        string
       +--ro one-way-delay?             uint32
       +--ro two-way-delay?             uint32
       +--ro one-way-delay-min?         uint32
       +--ro one-way-delay-max?         uint32
       +--ro two-way-delay-min?         uint32
       +--ro two-way-delay-max?         uint32
       +--ro one-way-delay-variation?   uint32
       +--ro two-way-delay-variation?   uint32
       +--ro one-way-packet-loss?       decimal64
       +--ro two-way-packet-loss?       decimal64
       +--ro utilized-bandwidth?        rt:bandwidth-ieee-float32
       +--ro utilized-percentage?       decimal64
       +--ro te-ref?                    -> /te:te/tunnels/tunnel/name

But Xufeng and Igor suggested that we need to augment one-way-delay and two-way-delay from actual LSP container in the TE-tunnel model while augmenting all other packet related data from ietf-te-mpls. 

If we were to augment one-way and two-way-delay from TE-tunnel model, we need to define these data in the TE-tunnel model. Current thinking is to do the following:

augment /te:te/te:tunnels/te:tunnel/te:p2p-primary-paths/te:p2p-primary-path/te:state/te:lsps/te:lsp

+--ro te-telemetry
       +--ro one-way-delay?             uint32
       +--ro two-way-delay?             uint32  

augment /te:te/te:tunnels/te:tunnel/te: p2p-primary-paths/te: p2p-primary-path/te: p2p-reverse-primary-path/te:state/te:lsps/te:lsp

+--ro te-telemetry
       +--ro one-way-delay?             uint32
       +--ro two-way-delay?             uint32   

augment /te:te/te:tunnels/te:tunnel/te:p2p-secondary-paths/te:p2p-secondary-path/te:state/te:lsps/te:lsp

+--ro te-telemetry
       +--ro one-way-delay?             uint32
       +--ro two-way-delay?             uint32

**Comment by ietf-mpls-yang** [comment]
this is a duplicate issue to issue #24
