### ISSUE TITLE
generic-computed-path-properties;

### ISSUE THREAD

**Issue by ylee-tx** [ietf-mpls-yang/te#20]
Hi Xufeng,

Should  "generic-computed-path-properties;" be updated with "generic-path-properties" to be consistent with te-types? 

Young

**Comment by ietf-mpls-yang** [comment]
to modify TE model to use the generic-path-properties instead of path-properties grouping

**Comment by ietf-mpls-yang** [comment]
Italo: path-srlgs and path-affinities
AI (Italo): check if path-computation can accept named affinities

**Comment by ietf-mpls-yang** [comment]
this is addressed in commit c3f57b86c15e866c440a4616e0e1b91aecd86ed9
