### ISSUE TITLE
explicit-route-object homonymy

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-mpls-yang/te#23]
In the tunnel model there is the definition of the container explicit-route-object that is inserted in two different grouping , path-route-object used to indicate include/exclude resources in path computation and named-explicit-paths as input to paths configuration.

It would be good to avoid the usage of the same name with different syntax  in two different context. A different name with a clear description of the scope would be beneficial . 

Her the groupings and related tree :
grouping path-route-objects {
    description
      "List of EROs to be included or excluded when performing
       the path computation.";
    container explicit-route-objects {
      description
        "Container for the exclude route object list";
      list route-object-exclude-always {
        key index;
        description
          "List of explicit route objects to always exclude
           from path computation";
        uses te-types:explicit-route-hop;
      }
      list route-object-include-exclude {
        key index;
        description
          "List of explicit route objects to include or
           exclude in path computation";
        leaf explicit-route-usage {
          type identityref {
            base te-types:route-usage-type;
          }
          description "Explicit-route usage.";
        }
        uses te-types:explicit-route-hop;
      }
    }
  }
 
  grouping named-explicit-paths {
    description
      "Global explicit path configuration
      grouping";
    container named-explicit-paths {
      description "TE named explicit path container";
      list named-explicit-path {
        key "name";
        description
          "A list of explicit paths";
        uses named-explicit-paths_config;
        container explicit-route-objects {
          description "Explicit route objects container";
          list explicit-route-object {
            key "index";
            description
              "List of explicit route objects";
            leaf explicit-route-usage {
              type identityref {
                base te-types:route-usage-type;
              }
              description "An explicit-route hop action.";
            }
            uses te-types:explicit-route-hop;
          }
        }
      }
    }
  }

below the related tree:

     |  +--rw named-explicit-paths
     |  |  +--rw named-explicit-path* [name]
     |  |     +--rw name                      string
     |  |     +--rw explicit-route-objects
     |  |        +--rw explicit-route-object* [index]
     |  |           +--rw explicit-route-usage?   identityref
     |  |           +--rw index                   uint32
     |  |           +--rw (type)?
     |  |              +--:(numbered)
     |  |                ...
     |  |              +--:(as-number)
     |  |                ...
     |  |              +--:(unnumbered)
     |  |                ...
     |  |              +--:(label)
     |  |                 ...
     |  |   ... 
     |  +--rw named-path-constraints
     |  |  +--rw named-path-constraint* [name] {te-types:named-path-constraints}?
     |  |     |    ...
     |  |     +--rw explicit-route-objects
     |  |     |  +--rw route-object-exclude-always* [index]
     |  |     |  |  +--rw index             uint32
     |  |     |  |  +--rw (type)?
     |  |     |  |     +--:(numbered)
     |  |     |  |     |     ...
     |  |     |  |     +--:(as-number)
     |  |     |  |     |     ...
     |  |     |  |     +--:(unnumbered)
     |  |     |  |     |     ...
     |  |     |  |     +--:(label)
     |  |     |  |           ...
     |  |     |  +--rw route-object-include-exclude* [index]
     |  |     |     +--rw explicit-route-usage?   identityref
     |  |     |     +--rw index                   uint32
     |  |     |     +--rw (type)?
     |  |     |        +--:(numbered)
     |  |     |        |     ...
     |  |     |        +--:(as-number)
     |  |     |        |     ...
     |  |     |        +--:(unnumbered)
     |  |     |        |     ...
     |  |     |        +--:(label)
     |  |     |              ...

**Comment by ietf-mpls-yang** [comment]
Converged on removing named-explicit-path and keeping it under constraints

**Comment by ietf-mpls-yang** [comment]
Addressed in latest model
