### ISSUE TITLE
Bidirectional tunnel configuration

### ISSUE THREAD

**Issue by italobusi** [ietf-mpls-yang/te#25]
Three types of bidirectional tunnels can be considered:

- An associated bidirectional non co-routed tunnel which is supported by associated unidirectional LSPs which can take different routes in the forward and backward directions
- An associated bidirectional co-routed tunnel which is supported by associated unidirectional LSPs which take the same route in the forward and backward directions
- A bidirectional (co-routed, non associated) tunnel which is supported by bidirectional LSPs (e.g., OTN or WDM connections)

Is this assumption correct?
 
Associated bidirectional tunnel can be configured using the attributes in the bidirectional/association container, and, in particular, the type attribute allows distinguishing between co-routed and non co-routed associated bidirectional tunnels.
 
If these attributes are missing, it is not clear how to know whether the tunnel is unidirectional or bidirectional (co-routed, non associated).
 
In case of associated bidirectional tunnels, for each primary path, the p2p-primary-path would contain the path constraints/state for the unidirectional primary path in the forward direction (including the unidirectional LSP in the forward direction) as well as the associated unidirectional p2p-reverse-primary-path which would contain the path constraints/state for the unidirectional primary path in the reverse direction (including the unidirectional LSP in the reverse direction).

Is this correct?
 
If this is correct, it is not clear how to associate two existing unidirectional LSPs (assuming they have been setup using two unidirectional tunnels) into a single associated bidirectional tunnel.

It is also not clear how the secondary paths are configured and in particular the meaning of the p2p-reverse-primary-path container used within the p2p-reverse-primary-path container.

Looking at the Global Association Source in RFC 7551, it seems that it should contain the Global_ID of the source node. Therefore its syntax should be te-types:te-global-id instead of inet:ip-address.
 
Also the reference for the provisioning attribute should be updated to RFC 7551:
 
```
    leaf provisioning {
      type identityref {
        base te-types:bidir-provisioning-mode;
      }
      description
        "Describes the provisioning model of the
        associated bidirectional LSP";
      reference
        "draft-ietf-teas-mpls-tp-rsvpte-ext-
        associated-lsp, section-3.2";
    }

```

**Comment by italobusi** [comment]
Based on today's call discussion, the YANG tree should be modified as follows:

```
     |  |  +--rw bidirectional
     |  |  |  +--rw enabled?            boolean
     |  |  |  +--rw associated?         boolean
     |  |  |  +--rw association
     |  |  |     +--rw id?              uint16
     |  |  |     +--rw source?          inet:ip-address
     |  |  |     +--rw global-source?   inet:ip-address
     |  |  |     +--rw type?            identityref
     |  |  |     +--rw provisioning?    identityref
```

**Comment by italobusi** [comment]
Based on today's call discussion, more discussion is needed to have a common view on how to model the "paths" for different bidirectional tunnel types

In case of native bidirectional tunnels:
- the path constraints for both directions are configured in the p2p-primary-path container 
  - no path constraints can be configured in the p2p-reverse-primary-path container
- the path properties for the path in the forward direction are reported in the p2p-primary-path container
- the path properties for the path in the revers direction are reported in the p2p-reverse-primary-path container

To continue in the next calls

**Comment by ietf-mpls-yang** [comment]
bidirectional_bool: 1 tunnel native bidirectional / (corouted - non-courouted)
associated_bool: not needed
configured list of association under the tunnel (key is 4-tuple)
we need introduce association types (known to date)

|  |  +--rw bidirectional
     |  |  |  +--rw enabled?            boolean
     |  |  |  +--rw associated?         boolean
     |  |  |  +--rw association
     |  |  |     +--rw id?              uint16
     |  |  |     +--rw source?          inet:ip-address
     |  |  |     +--rw global-source?   inet:ip-address
     |  |  |     +--rw type?            identityref
     |  |  |     +--rw provisioning?    identityref

**Comment by ietf-mpls-yang** [comment]
Key:
List of Below Associations:
Type, Association ID,  Association Source,
    EXT: Global Association Source, Extended Association ID
Extended Association ID encodings per type:
Array of bytes - variable Length
switch (on obj-type):
 base: (1/2)
 extended: (199)

**Comment by ietf-mpls-yang** [comment]
Association types are defined in:
https://www.iana.org/assignments/gmpls-sig-parameters/gmpls-sig-parameters.xhtml#gmpls-sig-parameters-9

LIST (key)
 1. BIDIR:
      BASE

 2. DISJ:
      BASE

**Comment by ietf-mpls-yang** [comment]
Addressed.
AI (Italo): may open a new issue for the reverse path
