### ISSUE TITLE
Label restrictions

### ISSUE THREAD

**Issue by italobusi** [ietf-mpls-yang/te#29]
TE Tunnel defines a label-set information, using the label-set-info grouping defined in te-types:
```
     |  |     |     +--rw label-set* [inclusive-exclusive label-start]
     |  |     |        +--rw inclusive-exclusive    enumeration
     |  |     |        +--rw label-start            rt-types:generalized-label
     |  |     |        +--rw label-end?             rt-types:generalized-label
     |  |     |        +--rw range-bitmap?          binary
```

TE Topology defines a label-restriction information, defining another (similar) connectivity-label-restriction-list grouping:
```
          |  +--rw label-restriction* [index]
          |  |  +--rw index                    uint32
          |  |  +--rw inclusive-exclusive?     enumeration
          |  |  +--rw label-start
          |  |  |  +--rw te-label
          |  |  |     +--rw (technology)?
          |  |  |     |  +--:(generic)
          |  |  |     |     +--rw generic?     rt-types:generalized-label
          |  |  |     +--rw direction?         te-label-direction
          |  |  +--rw label-end
          |  |  |  +--rw te-label
          |  |  |     +--rw (technology)?
          |  |  |     |  +--:(generic)
          |  |  |     |     +--rw generic?     rt-types:generalized-label
          |  |  |     +--rw direction?         te-label-direction
          |  |  +--rw range-bitmap?            binary
```

The two approaches need to be reconciled, taking into account the need to specify also technology-specific extensions.

The available ODU bandwidth and label information defined in current OTN topology model ([draft-ietf-ccamp-otn-tunnel-model-01](https://tools.ietf.org/html/draft-ietf-ccamp-otn-tunnel-model-01)) is:
```
       +--rw available-odu-info* [priority]
       |  +--rw priority    uint8
       |  +--rw odulist* [odu-type]
       |  |  +--rw odu-type     identityref
       |  |  +--rw number?      uint16
       |  |  +--rw tpn-range?   string
       |  +--rw ts-range?   string
       +--rw tsg?                  identityref
       +--rw distance?             uint32
```

The information of available bandwidth and available label should be split to match the generic model constructs but it would be worthwhile to keep the structure of the information.

The available VLAN range information defined incurrent ETH topology model ([draft-zheng-ccamp-client-topo-yang-02](https://tools.ietf.org/html/draft-zheng-ccamp-client-topo-yang-02)) is:
`    +--rw available-vlan-range?   etht-types:vid-range-type`

See also: https://github.com/haomianzheng/IETF-ACTN-YANG-Model/issues/3

**Comment by italobusi** [comment]
Unstructured notes taken/shared during the audio on April 26, 2018:

[notes-20180426-1.txt](https://github.com/ietf-mpls-yang/te/files/1952056/notes-20180426-1.txt)

[notes-20180426-2.txt](https://github.com/ietf-mpls-yang/te/files/1952057/notes-20180426-2.txt)

**Comment by ietf-mpls-yang** [comment]
AI (Italo/Xufeng): follow up on this and may close next meeting
Do we need a step?

**Comment by ietf-mpls-yang** [comment]
AI(Xufeng/Italo): TE topology model needs to use the generic type for label-set

**Comment by ietf-mpls-yang** [comment]
YANG (binary) to JSON - can you investigate the type it translates to?

**Comment by italobusi** [comment]
Re: YANG (binary) to JSON

It seems that YANG binary are encoded in JSON string using base64 encoding:

https://tools.ietf.org/html/rfc7951#section-6.6

Therefore there should be no JSON-encoding issue with using YANG binary for the label-bitmap

**Comment by ietf-mpls-yang** [comment]
to review the latest commit 4ceae2d
