### ISSUE TITLE
bi-directional PM attributes

### ISSUE THREAD

**Issue by younglee-ietf** [ietf-mpls-yang/te#38]
Hi, 

Current TE-Types defines PM attributes grouping for TE-link for uni-directional PM. This grouping is used for various augmentation above link such as VN, tunnel, LSPs. Based on private talk with Rakesh and Pavan and Tarek, we need to define bi-directional PM attributes grouping in the TE-types module.

**Comment by ietf-mpls-yang** [comment]
Need new PM metrics per LSP
PM metrics per LSP can be bidirectional (assuming LSP is bidir)
PM metrics for links -- should they be bidir?

**Comment by ietf-mpls-yang** [comment]
Do we need persistant PM metrics per tunnel
(same grouping)
For bidir metrics: (two-way metrics)?

**Comment by ietf-mpls-yang** [comment]
Change to one-way-delay and two-way-delay
look into name clash "residual-bandwidth" on per link
Leave PM groupings in TE-TYPEs. Add in description that this grouping is applicable to packet performance metrics
They are used already in MPLS-TE-TUNNEL model and L3 TE topology will use it

draft-ietf-teas-te-types:
TE-TYPEs

**Comment by ietf-mpls-yang** [comment]
AI (Rakesh and Young): please review the PM metrics and provide new groupings

**Comment by younglee-ietf** [comment]
Take a look at the new suggested groupings for performance-metric-attributes. Two changes were made:

1.	Separate grouping for links and connections (as some attributes are only applicable to links such as bandwidth related attributes (e.g., residual b/w))
2.	Introduced two-way attributes. 

See if this makes sense. If there is a better way, please suggest it. 

[groupings for PM data_TE Types.docx](https://github.com/ietf-mpls-yang/te/files/2264225/groupings.for.PM.data_TE.Types.docx)
