### ISSUE TITLE
Add a label step in the label range include/exclude

### ISSUE THREAD

**Issue by ietf-mpls-yang** [ietf-mpls-yang/te#42]

**Comment by italobusi** [comment]
Please note that there is some duplication of information between the direction attributes in label-start and label-end containers (also in te-topology).

There is also duplication with the external forward/reverse containers (which are not used in the te-topology).

See comments from past discussion in:

https://github.com/ietf-mpls-yang/te/commit/4ceae2d61d8fe1190c6a123f3d34a88892a3ec6a

TE Tunnel Tree extract:

```
     |  |     +--rw path-in-segment!
     |  |     |  +--rw forward
     |  |     |  |  +--rw label-restrictions
     |  |     |  |     +--rw label-restriction* [index]
     |  |     |  |        +--rw restriction?    enumeration
     |  |     |  |        +--rw index           uint32
     |  |     |  |        +--rw label-start
     |  |     |  |        |  +--rw te-label
     |  |     |  |        |     +--rw (technology)?
     |  |     |  |        |     |  +--:(generic)
     |  |     |  |        |     |     +--rw generic?
     rt-types:generalized-label
     |  |     |  |        |     +--rw direction?
     te-label-direction
     |  |     |  |        +--rw label-end
     |  |     |  |        |  +--rw te-label
     |  |     |  |        |     +--rw (technology)?
     |  |     |  |        |     |  +--:(generic)
     |  |     |  |        |     |     +--rw generic?
     rt-types:generalized-label
     |  |     |  |        |     +--rw direction?
     te-label-direction
     |  |     |  |        +--rw range-bitmap?   binary
     |  |     |  +--rw reverse
     |  |     |     +--rw label-restrictions
     |  |     |        +--rw label-restriction* [index]
     |  |     |           +--rw restriction?    enumeration
     |  |     |           +--rw index           uint32
     |  |     |           +--rw label-start
     |  |     |           |  +--rw te-label
     |  |     |           |     +--rw (technology)?
     |  |     |           |     |  +--:(generic)
     |  |     |           |     |     +--rw generic?
     rt-types:generalized-label
     |  |     |           |     +--rw direction?
     te-label-direction
     |  |     |           +--rw label-end
     |  |     |           |  +--rw te-label
     |  |     |           |     +--rw (technology)?
     |  |     |           |     |  +--:(generic)
     |  |     |           |     |     +--rw generic?
     rt-types:generalized-label
     |  |     |           |     +--rw direction?
     te-label-direction
     |  |     |           +--rw range-bitmap?   binary

```
          |  |  +--ro label-restrictions
          |  |  |  +--ro label-restriction* [index]
          |  |  |     +--ro restriction?    enumeration
          |  |  |     +--ro index           uint32
          |  |  |     +--ro label-start
          |  |  |     |  +--ro te-label
          |  |  |     |     +--ro (technology)?
          |  |  |     |     |  +--:(generic)
          |  |  |     |     |     +--ro generic?
          |  |  |     |     |             rt-types:generalized-label
          |  |  |     |     +--ro direction?       te-label-direction
          |  |  |     +--ro label-end
          |  |  |     |  +--ro te-label
          |  |  |     |     +--ro (technology)?
          |  |  |     |     |  +--:(generic)
          |  |  |     |     |     +--ro generic?
          |  |  |     |     |             rt-types:generalized-label
          |  |  |     |     +--ro direction?       te-label-direction
          |  |  |     +--ro range-bitmap?   binary

**Comment by ietf-mpls-yang** [comment]
Generic Label Range:
====================

   +--rw label-restriction* [index]
   |  +--rw index                  uint32
   |  +--rw inclusive-exclusive?   enumeration
   |  +--rw label-start
   |  |  +--rw te-label
   |  |     +--rw (technology)?
   |  |     |  +--:(generic)
   |  |     |     +--rw generic?
   |  |     |             rt-types:generalized-label
   |  |     +--rw direction?       te-label-direction
   |  +--rw label-end
   |  |  +--rw te-label
   |  |     +--rw (technology)?
   |  |     |  +--:(generic)
   |  |     |     +--rw generic?
   |  |     |             rt-types:generalized-label
   |  |     +--rw direction?       te-label-direction
+  |  +--rw label-step
+  |  |  +--rw (technology)?
+  |  |     +--:(generic)
+  |  |        +--rw generic?      uint32          // step for generic label
   |  +--rw range-bitmap?          binary

**Comment by ietf-mpls-yang** [comment]
¦|  |     |  |     +--rw label-restriction* [index]
    ¦|  |     |  |        +--rw restriction?    enumeration
    ¦|  |     |  |        +--rw index           uint32
    ¦|  |     |  |        +--rw label-start
    ¦|  |     |  |        |  +--rw te-label
    ¦|  |     |  |        |     +--rw (technology)?
    ¦|  |     |  |        |     |  +--:(generic)
    ¦|  |     |  |        |     |     +--rw generic?   rt-types:generalized-label
    ¦|  |     |  |        |     +--rw direction?       te-label-direction
    ¦|  |     |  |        +--rw label-end
    ¦|  |     |  |        |  +--rw te-label
    ¦|  |     |  |        |     +--rw (technology)?
    ¦|  |     |  |        |     |  +--:(generic)
    ¦|  |     |  |        |     |     +--rw generic?   rt-types:generalized-label
    ¦|  |     |  |        |     +--rw direction?       te-label-direction
    ¦|  |     |  |        +--rw label-step
    ¦|  |     |  |        |  +--rw te-label
    ¦|  |     |  |        |     +--rw (technology)?
    ¦|  |     |  |        |     |  +--:(generic)
    ¦|  |     |  |        |     |     +--rw generic?   rt-types:generalized-label                                                                                                                                     ¦|  |     |  |        +--rw range-bitmap?   binary

**Comment by ietf-mpls-yang** [comment]
label-step is technology specific
generic is 32 bit number

**Comment by ietf-mpls-yang** [comment]
32 bit positive number

**Comment by ietf-mpls-yang** [comment]
Individual labels:
  1 number in label-start

Range:
  1 number in label-start (start < end)
  1 number in label-end
  1 number in label-step (increment starting from start)

**Comment by ietf-mpls-yang** [comment]
Range:
1 number in label-start
1 number in label-end
1 number in label-step (increment or decrement starting from start)

**Comment by ietf-mpls-yang** [comment]
no need for forward/reverse
label-start and label-end labels will be in same direction

**Comment by ietf-mpls-yang** [comment]
addressed

**Comment by ietf-mpls-yang** [comment]
to add must check for label-start and label-end to have the same direction (if both configured)

**Comment by ietf-mpls-yang** [comment]
Add in description that start/stop range have to be consistent with the sign of the step

**Comment by ietf-mpls-yang** [comment]
Add a simple example in the description

**Comment by ietf-mpls-yang** [comment]
addressed
