### ISSUE TITLE
Duplicated id/index for explicit-route-hop?

### ISSUE THREAD

**Issue by italobusi** [ietf-mpls-yang/te#43]
In TE Topology tree, it seems that there is some duplication between the path-element-id and the index of path-element:

```
                   |  |  +--rw path-element* [path-element-id]
                   |  |     +--rw path-element-id        uint32
                   |  |     +--rw index?                 uint32
```

**Comment by italobusi** [comment]
The issue seems caused by the fact that TE Topology YANG module defines a path-element list which the path-element-id as an index and which uses the te-types:explicit-route-hop while the te-types:explicit-route-hop defines an index attribute to be used as an index by the TE Tunnel model

Extracts from the TE Topology YANG model:

```
         list path-element {
           key "path-element-id";
           description
             "A list of path elements describing the service path.";
           leaf path-element-id {
             type uint32;
             description "To identify the element in a path.";
           }
           uses te-path-element;
         }

<...>
     grouping te-path-element {
       description
         "A group of attributes defining an element in a TE path
          such as TE node, TE link, TE atomic resource or label.";
       uses te-types:explicit-route-hop;
     } // te-path-element
```
Extract from TE-Types YANG module:

```
  grouping explicit-route-hop {
    description
      "The explicit route subobject grouping";
    leaf index {
      type uint32;
      description "ERO subobject index";
    }
```

Some extracts from the TE Tunnel YANG model:

```
      list route-object-exclude-always {
        key index;
        description
          "List of explicit route objects to always exclude
           from path computation";
        uses te-types:explicit-route-hop;
      }
```

**Comment by italobusi** [comment]
Considering the status of the TE Topology draft, I think we have three options:

1) ignore the issue (the index attribute in te-topology is optional and people can just not implement it)
2) remove the index attribute from te-types:explicit-route-hop and add it to all the points in the te-tunnel model where this grouping is used
3) remove the index attribute from te-types:explicit-route-hop, create a new grouping within the te-tunnel model with this attribute added and replace all the instances using the te-types:explicit-route-hop to use the new grouping

Option 3 seems the most clean and the one with minimum impact to the te-tunnel YANG model

**Comment by ietf-mpls-yang** [comment]
To address using option 2) to add index everywhere where the explicit-route-hop is used.

**Comment by ietf-mpls-yang** [comment]
addressed
