### ISSUE TITLE
Incorrect base for path-signaling-rsvpte, path-signaling-sr in te-types.yang

### ISSUE THREAD

**Issue by dhruvdhody-huawei** [ietf-mpls-yang/te#5]
OLD: 
  identity path-signaling-type {
    description
      "Base identity from which specific path signaling
       types are derived.";
  }

  identity path-signaling-rsvpte {
    base tunnel-type;
    description
      "RSVP-TE path signaling type";
  }

  identity path-signaling-sr {
    base tunnel-type;
    description
      "Segment-routing path signaling type";
  }
NEW:
  identity path-signaling-type {
    description
      "Base identity from which specific path signaling
       types are derived.";
  }

  identity path-signaling-rsvpte {
    base path-signaling-type;
    description
      "RSVP-TE path signaling type";
  }

  identity path-signaling-sr {
    base path-signaling-type;
    description
      "Segment-routing path signaling type";
  }

**Comment by ietf-mpls-yang** [comment]
Thanks Dhruv for reporting this. I've fixed this and removed a  redundant identity.
