### ISSUE TITLE
Use of topology-id

### ISSUE THREAD

**Issue by italobusi** [ietf-mpls-yang/te#6]
The topology-id is used to identify  in which topology the tunnel is computed:

https://github.com/ietf-mpls-yang/te/blob/b713c88398ef2594a637586f8f44418bfd3396d3/ietf-te.yang#L1348

However, it seems that a topology is uniquely identified using provider-id, client-id and topology-id:
https://tools.ietf.org/html/draft-ietf-teas-yang-te-topo-12#section-5.4

I am wondering whether it is not worthwhile defining the following grouping in ietf-te-types and use it here:

```
	grouping te-topology-identifier {
		leaf provider-id {
			type te-types:te-global-id;
			description
				"An identifier to uniquely identify a provider.";
		}
		leaf access-client-id {
			type te-types:te-global-id;
			description
				"An identifier to uniquely identify a client.";
		}
		leaf access-topology-id {
			type te-types:te-topology-id;
			description
				"Identifies the topology.";
		}
	}

```

**Comment by ietf-mpls-yang** [comment]
topology-id is enough to identify a specific native topology
It is OK to use a grouping with 3 leafs as suggested. We will copy the topology model leaves

**Comment by ietf-mpls-yang** [comment]
Added to te-types module
