### ISSUE TITLE
Grouping common-constraints_config

### ISSUE THREAD

**Issue by italobusi** [ietf-mpls-yang/te#7]
Why the ietf-te module re-defines this grouping rather than using the same grouping defined in ietf-te-types?

https://github.com/ietf-mpls-yang/te/blob/b713c88398ef2594a637586f8f44418bfd3396d3/ietf-te.yang#L1344-L1385

https://github.com/ietf-mpls-yang/te/blob/master/ietf-te-types.yang#L1850-L1896

**Comment by ietf-mpls-yang** [comment]
I removed the redundant one in  ietf-te module and relied on the grouping in ietf-te-types
