### ISSUE TITLE
Move lockout-normal to under

### ISSUE THREAD

**Issue by ietf-mpls-yang** [ietf-mpls-yang/te#8]
|  |  +--rw protection
       |  |  |  +--rw enable?                         boolean
       |  |  |  +--rw protection-type?                identityref
       |  |  |  +--rw protection-reversion-disable?   boolean
       |  |  |  +--rw hold-off-time?                  uint32
       |  |  |  +--rw wait-to-revert?                 uint16
       |  |  |  +--rw lockout-of-normal?              boolean
XX: Move out from under tunnel to primary and secondary path.

       |  |  |  +--rw freeze?                         boolean
XX: same.

       |  |  +--rw restoration
       |  |  |  +--rw enable?                          boolean
       |  |  |  +--rw restoration-type?                identityref
       |  |  |  +--rw restoration-scheme?              identityref
       |  |  |  +--rw restoration-reversion-disable?   boolean
       |  |  |  +--rw hold-off-time?                   uint32
       |  |  |  +--rw wait-to-restore?                 uint16
       |  |  |  +--rw wait-to-revert?                  uint16

**Comment by italobusi** [comment]
It seems to me that this issue has been superseded by issue #9 and it could also be close

Am I missing anything?

**Comment by ietf-mpls-yang** [comment]
This comment was addressed in latest model, so closing
