### ISSUE TITLE
State only leaf

### ISSUE THREAD

**Issue by ietf-mpls-yang** [ietf-mpls-yang/te#9]
|  |  +--rw protection
       |  |  |  +--rw enable?                         boolean
       |  |  |  +--rw protection-type?                identityref
       |  |  |  +--rw protection-reversion-disable?   boolean
       |  |  |  +--rw hold-off-time?                  uint32
       |  |  |  +--rw wait-to-revert?                 uint16
       |  |  |  +--rw lockout-of-normal?              boolean
       |  |  |  +--rw freeze?                         boolean
XX: move freeze and lockout to state-only. These should not be configurable

**Comment by italobusi** [comment]
It seems that this issue has been already fixed in the latest version of the YANG model and tree on GitHub

Could we close the issue or is there anything that needs further discussion/review?

**Comment by ietf-mpls-yang** [comment]
issue seems closed
